apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn-flux-integration
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keptn-flux-integration
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keptn-flux-integration
      version: 0.16.5
  interval: 5m0s
  values:
    keptn:
      url: https://keptn.ortelius.io/api/v1/event
