apiVersion: v1
kind: Secret
metadata:
  name: keptn-flux-integration
  namespace: flux-system
stringData:
  address: http://keptn-flux-integration.flux-system.svc.cluster.local:80
  headers: |
     Content-Type: application/json
     x-token: <keptn-api-here>
  body: |
    {
      "data": {
        "configurationChange": {},
        "labels": {
          "servicename": "{{.keptnService}}"
        },
        "project": "{{.keptnProject}}",
        "service": "{{.keptnService}}",
        "stage": "{{.keptnStage}}"
      },
      "source": "flux",
      "specversion": "1.0",
      "type": "{{.keptnType}}",
      "shkeptnspecversion": "0.2.3"
    }
