NAME: keptn-flux-integration-1657707201
LAST DEPLOYED: Wed Jul 13 20:13:23 2022
NAMESPACE: flux-system
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: keptn-flux-integration/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "keptn-flux-integration-1657707201-test-connection"
  labels:
    helm.sh/chart: keptn-flux-integration-0.16.1
    app.kubernetes.io/name: keptn-flux-integration
    app.kubernetes.io/instance: keptn-flux-integration-1657707201
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['keptn-flux-integration.flux-system.svc.cluster.local:80']
  restartPolicy: Never
MANIFEST:
---
# Source: keptn-flux-integration/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-flux-integration-1657707201
  labels:
    helm.sh/chart: keptn-flux-integration-0.16.1
    app.kubernetes.io/name: keptn-flux-integration
    app.kubernetes.io/instance: keptn-flux-integration-1657707201
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
---
# Source: keptn-flux-integration/templates/keptn-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: podtato-head-podtato-kustomize
  namespace: flux-system
stringData:
  address: http://keptn-flux-integration.flux-system.svc.cluster.local:80
  headers: |
     Content-Type: application/json
     x-token: mmhdUVgQAbX04NOuKSKwBTkYIRKoa2wshtgMFiGhYyHr6
  body: |
    {
      "data": {
        "configurationChange": {},
        "labels": {
          "servicename": ""
        },
        "project": "",
        "service": "",
        "stage": ""
      },
      "source": "flux",
      "specversion": "1.0",
      "type": "",
      "shkeptnspecversion": "0.2.3"
    }
---
# Source: keptn-flux-integration/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: keptn-flux-integration
  labels:
    helm.sh/chart: keptn-flux-integration-0.16.1
    app.kubernetes.io/name: keptn-flux-integration
    app.kubernetes.io/instance: keptn-flux-integration-1657707201
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: keptn-flux-integration
    app.kubernetes.io/instance: keptn-flux-integration-1657707201
---
# Source: keptn-flux-integration/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-flux-integration-1657707201
  labels:
    helm.sh/chart: keptn-flux-integration-0.16.1
    app.kubernetes.io/name: keptn-flux-integration
    app.kubernetes.io/instance: keptn-flux-integration-1657707201
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keptn-flux-integration
      app.kubernetes.io/instance: keptn-flux-integration-1657707201
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keptn-flux-integration
        app.kubernetes.io/instance: keptn-flux-integration-1657707201
    spec:
      serviceAccountName: keptn-flux-integration-1657707201
      securityContext:
        {}
      containers:
        - name: keptn-flux-integration
          securityContext:
            {}
          image: "bradmccoydev/keptn-flux-integration:latest"
          imagePullPolicy: Always
          # envFrom:
          #   - secretRef:
          #       name: keptn-secret
          env:
            - name: KEPTN_FLUX_INTEGRATION_PORT
              value: "80" #TODO: use value service.port but cast as string
            - name: KEPTN_URL
              value: https://keptn.ortelius.io/api/v1/event
            - name: FLUX_NAMESPACE
              value: flux-system
            - name: FLUX_PROVIDER_GROUP
              value: notification.toolkit.fluxcd.io
            - name: FLUX_PROVIDER_VERSION
              value: v1beta1
            - name: FLUX_PROVIDER_RESOURCE
              value: providers
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
          resources:
            {}
---
# Source: keptn-flux-integration/templates/app.yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podtato-head-podtato-kustomize
spec:
  summary: default
  providerRef:
    name: podtato-head-podtato-kustomize
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      namespace: podtato-kustomize
      name: podtato-head
      matchLabels:
        app.kubernetes.io/name: podtato-head
---
# Source: keptn-flux-integration/templates/app.yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: podtato-head-podtato-kustomize
  labels:
    keptnProject: gsoc
    keptnService: podtato-head
    keptnStage: qa
    keptnType: sh.keptn.event.qa.delivery.triggered
spec:
  type: generic
  address: http://keptn-flux-integration.flux-system.svc.cluster.local:80
  secretRef:
    name: podtato-head-podtato-kustomize

