{{- range $app := .Values.flux.apps }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: {{ .name }}-{{ .namespace }}
spec:
  summary: default
  providerRef:
    name: {{ .name }}-{{ .namespace }}
  eventSeverity: info
  eventSources:
    - kind: {{ .kind }}
      namespace: {{ .namespace }}
      name: {{ .name }}
      {{- with .matchLabels }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: {{ .name }}-{{ .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  type: generic
  address: {{ .integrationUrl }}
  secretRef:
    name: {{ .name }}-{{ .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-{{ .namespace }}
stringData:
  address: {{ .integrationUrl }}
  headers: |
     Content-Type: application/json
     x-token: update-your-keptn-token-here
  body: |
    {
      "data": {
        "configurationChange": {},
        "labels": {
          "servicename": "{{.keptnService}}",
        },
        "project": "{{.keptnProject}}",
        "service": "{{.keptnService}}",
        "stage": "{{.keptnStage}}"
      },
      "source": "flux",
      "specversion": "1.0",
      "type": "{{.keptnType}}",
      "shkeptnspecversion": "0.2.3"
    }
{{- end }}
