{{- if .Values.flux.demo.enabled -}}
{{- range $app := .Values.flux.demo.apps }}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: {{ .name }}-{{ .namespace }}
spec:
  summary: default
  providerRef:
    name: {{ .name }}-{{ .namespace }}
  eventSeverity: info
  eventSources:
    - kind: {{ .kind }}
      name: {{ .name }}
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: keptn
    - kind: HelmChart
      name: "*"
    - kind: HelmRepository
      name: "*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: {{ .name }}-{{ .namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  type: generic
  address: {{ .integrationUrl }}
  secretRef:
    name: {{ .name }}-{{ .namespace }}
---
{{- end }}
{{- end }}
