apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keptn-flux-integration.fullname" . }}
  labels:
    {{- include "keptn-flux-integration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keptn-flux-integration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keptn-flux-integration.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keptn-flux-integration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # envFrom:
          #   - secretRef:
          #       name: keptn-secret
          env:
            - name: KEPTN_FLUX_INTEGRATION_PORT
              value: "80" #TODO: use value service.port but cast as string
            - name: KEPTN_URL
              value: {{ .Values.keptn.url }}
            - name: FLUX_NAMESPACE
              value: {{ .Values.flux.namespace }}
            - name: FLUX_PROVIDER_GROUP
              value: {{ .Values.flux.provider.groupVersionResource.group }}
            - name: FLUX_PROVIDER_VERSION
              value: {{ .Values.flux.provider.groupVersionResource.version }}
            - name: FLUX_PROVIDER_RESOURCE
              value: {{ .Values.flux.provider.groupVersionResource.resource }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
