{{- if .Values.keptn.install -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: keptn
  annotations:
    keptn.sh/managed-by: keptn
  labels:
    keptn.sh/managed-by: keptn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keptn
  namespace: keptn
spec:
  interval: 5m0s
  timeout: 120s
  url: https://charts.keptn.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn
  namespace: keptn
spec:
  chart:
    spec:
      chart: keptn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keptn
      version: {{ .Values.keptn.version }}
  interval: 5m0s
---
{{- end }}
