{{- if .Values.flux.alert.enabled -}}
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: {{ include "keptn-flux-integration.fullname" . }}
spec:
  summary: default
  providerRef:
    name: {{ include "keptn-flux-integration.fullname" . }}
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      namespace: {{ .Values.flux.alert.namespace }}
      name: "*"
      {{- with .Values.flux.alert.matchLabels }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}