apiVersion: v1
kind: Service
metadata:
  name: keptn-flux-integration
  labels:
    {{- include "keptn-flux-integration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "keptn-flux-integration.selectorLabels" . | nindent 4 }}
